name: glaucoma-detection-server
channels:
  - defaults
dependencies:
  - _tflow_select=2.2.0=eigen
  - abseil-cpp=20211102.0=hc377ac9_0
  - absl-py=1.4.0=py311hca03da5_0
  - aiohttp=3.9.3=py311h80987f9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - aom=3.6.0=h313beb8_0
  - astunparse=1.6.3=py_0
  - attrs=23.1.0=py311hca03da5_0
  - blas=1.0=openblas
  - blinker=1.6.2=py311hca03da5_0
  - blosc=1.21.3=h313beb8_0
  - bottleneck=1.3.7=py311hb9f6ed7_0
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotli-python=1.0.9=py311h313beb8_7
  - brunsli=0.1=hc377ac9_1
  - bzip2=1.0.8=h80987f9_5
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2024.3.11=hca03da5_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2024.2.2=py311hca03da5_0
  - cffi=1.16.0=py311h80987f9_0
  - cfitsio=3.470=h7f6438f_7
  - charls=2.2.0=hc377ac9_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py311hca03da5_0
  - cryptography=41.0.3=py311h3c57c4d_0
  - dav1d=1.2.1=h80987f9_0
  - flask=2.2.5=py311hca03da5_0
  - flask_cors=3.0.10=pyhd3eb1b0_0
  - flatbuffers=2.0.0=hc377ac9_0
  - freetype=2.12.1=h1192e45_0
  - frozenlist=1.4.0=py311h80987f9_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.1=h80987f9_3
  - google-auth=2.22.0=py311hca03da5_0
  - google-auth-oauthlib=0.5.2=py311hca03da5_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpc-cpp=1.48.2=h877324c_0
  - grpcio=1.48.2=py311h877324c_0
  - h5py=3.9.0=py311hba6ad2f_0
  - hdf5=1.12.1=h160e8cb_2
  - icu=68.1=hc377ac9_0
  - idna=3.4=py311hca03da5_0
  - imagecodecs=2023.1.23=py311h5e7c512_0
  - imageio=2.33.1=py311hca03da5_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jinja2=3.1.3=py311hca03da5_0
  - joblib=1.2.0=py311hca03da5_0
  - jpeg=9e=h80987f9_1
  - jxrlib=1.1=h1a28f6b_2
  - keras=2.12.0=py311hca03da5_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - krb5=1.20.1=h8380606_1
  - lazy_loader=0.3=py311hca03da5_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libaec=1.0.4=hc377ac9_1
  - libavif=0.11.1=h80987f9_0
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libcurl=8.2.1=h0f1d93c_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libnghttp2=1.52.0=h10c0552_1
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libssh2=1.10.0=h449679c_2
  - libtiff=4.5.1=h313beb8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libzopfli=1.0.3=hc377ac9_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - markdown=3.4.1=py311hca03da5_0
  - markupsafe=2.1.3=py311h80987f9_0
  - multidict=6.0.4=py311h80987f9_0
  - ncurses=6.4=h313beb8_0
  - networkx=3.1=py311hca03da5_0
  - numexpr=2.8.7=py311h6dc990b_0
  - numpy=1.23.5=py311hb2c0538_0
  - numpy-base=1.23.5=py311h9eb1c70_0
  - oauthlib=3.2.2=py311hca03da5_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=1.1.1w=h1a28f6b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=23.2=py311hca03da5_0
  - pandas=2.2.1=py311h7aedaa7_0
  - pillow=10.2.0=py311h80987f9_0
  - pip=23.3.1=py311hca03da5_0
  - protobuf=3.20.3=py311h313beb8_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py311hca03da5_0
  - pyopenssl=23.2.0=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.5=hc0d8a6c_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2023.3.post1=py311hca03da5_0
  - re2=2022.04.01=hc377ac9_0
  - readline=8.2=h1a28f6b_0
  - requests=2.31.0=py311hca03da5_1
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-image=0.22.0=py311h7aedaa7_0
  - scikit-learn=1.3.0=py311h7aedaa7_1
  - scipy=1.12.0=py311hc76d9b0_0
  - setuptools=68.2.2=py311hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h313beb8_1
  - sqlite=3.41.2=h80987f9_0
  - tensorboard=2.12.1=py311hca03da5_0
  - tensorboard-data-server=0.7.0=py311ha6e5c4f_0
  - tensorboard-plugin-wit=1.8.1=py311hca03da5_0
  - tensorflow=2.12.0=eigen_py311h689d69b_0
  - tensorflow-base=2.12.0=eigen_py311h0a52ebb_0
  - tensorflow-estimator=2.12.0=py311hca03da5_0
  - termcolor=2.1.0=py311hca03da5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2023.4.12=py311hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - typing_extensions=4.9.0=py311hca03da5_1
  - tzdata=2024a=h04d1e81_0
  - urllib3=1.26.18=py311hca03da5_0
  - werkzeug=2.3.8=py311hca03da5_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py311h80987f9_0
  - xz=5.4.6=h80987f9_0
  - yarl=1.9.3=py311h80987f9_0
  - zfp=1.0.0=h313beb8_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.5=hd90d995_0
prefix: /Users/shamith/miniconda3/envs/glaucoma-detection-server
